version: '3'
services:
  node_delay_job:
    image: node:11
    container_name: node_delay_job
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      DB_HOST: localhost
    volumes:
      - .:/app/
    ports:
      - 3000:3000
    working_dir: /app/
    network_mode: host
    command: npm run dev

  redis:
    container_name: redis_delay_job
    environment:
      REDIS_HOST: redis
    image: redis
    ports:
      - "6379:6379"

networks:
  net:
    driver: bridge